### ISSUE TITLE
Some configurations require no scope

### ISSUE THREAD

**Issue by MennovdHeuvel** [mlof/Magento.RestClient#7]
I'm using the RestClient to interact with Magento2 site that requires most calls to specify no scope at all. So an URL like {host}/rest/V1/... . This isn't currently possible, as the client "fixes" an empty scope to "default".

I've attached the quick fix that I'm currently using, but I'm sure you can come up with a more elegant approach.
[scope_fix.zip](https://github.com/mlof/Magento.RestClient/files/8688275/scope_fix.zip)

**Comment by mlof** [comment]
I like it. Quite simple. In all honesty, scopes in Magento have been the bane of my existence. I usually just use scope="all" which works fine for most things (except images)
